//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.42
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Dms.Data {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DataSetUnitInitialDataInfo")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSetUnitInitialDataInfo : System.Data.DataSet {
        
        private UnitInitialDataInfoDataTable tableUnitInitialDataInfo;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DataSetUnitInitialDataInfo() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DataSetUnitInitialDataInfo(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UnitInitialDataInfo"] != null)) {
                    base.Tables.Add(new UnitInitialDataInfoDataTable(ds.Tables["UnitInitialDataInfo"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UnitInitialDataInfoDataTable UnitInitialDataInfo {
            get {
                return this.tableUnitInitialDataInfo;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DataSetUnitInitialDataInfo cln = ((DataSetUnitInitialDataInfo)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["UnitInitialDataInfo"] != null)) {
                    base.Tables.Add(new UnitInitialDataInfoDataTable(ds.Tables["UnitInitialDataInfo"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableUnitInitialDataInfo = ((UnitInitialDataInfoDataTable)(base.Tables["UnitInitialDataInfo"]));
            if ((initTable == true)) {
                if ((this.tableUnitInitialDataInfo != null)) {
                    this.tableUnitInitialDataInfo.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DataSetUnitInitialDataInfo";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSetUnitInitialDataInfo.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableUnitInitialDataInfo = new UnitInitialDataInfoDataTable();
            base.Tables.Add(this.tableUnitInitialDataInfo);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeUnitInitialDataInfo() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DataSetUnitInitialDataInfo ds = new DataSetUnitInitialDataInfo();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void UnitInitialDataInfoRowChangeEventHandler(object sender, UnitInitialDataInfoRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class UnitInitialDataInfoDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnUNIT_NO;
            
            private System.Data.DataColumn columnID;
            
            private System.Data.DataColumn columnNAME;
            
            private System.Data.DataColumn columnDVNAME;
            
            private System.Data.DataColumn columnTYPE;
            
            private System.Data.DataColumn columnFORMAT;
            
            private System.Data.DataColumn columnLOW_VALUE;
            
            private System.Data.DataColumn columnHIGH_VALUE;
            
            private System.Data.DataColumn columnWORD_SIZE;
            
            private System.Data.DataColumn columnPOINT;
            
            private System.Data.DataColumn columnUNIT;
            
            private System.Data.DataColumn columnValueType;
            
            private System.Data.DataColumn columnADDRESS;
            
            private System.Data.DataColumn columnCHECK_ADDRESS;
            
            private System.Data.DataColumn columnSeqNo;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public UnitInitialDataInfoDataTable() {
                this.TableName = "UnitInitialDataInfo";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal UnitInitialDataInfoDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected UnitInitialDataInfoDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn UNIT_NOColumn {
                get {
                    return this.columnUNIT_NO;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn NAMEColumn {
                get {
                    return this.columnNAME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn DVNAMEColumn {
                get {
                    return this.columnDVNAME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TYPEColumn {
                get {
                    return this.columnTYPE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn FORMATColumn {
                get {
                    return this.columnFORMAT;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn LOW_VALUEColumn {
                get {
                    return this.columnLOW_VALUE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn HIGH_VALUEColumn {
                get {
                    return this.columnHIGH_VALUE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn WORD_SIZEColumn {
                get {
                    return this.columnWORD_SIZE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn POINTColumn {
                get {
                    return this.columnPOINT;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn UNITColumn {
                get {
                    return this.columnUNIT;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ValueTypeColumn {
                get {
                    return this.columnValueType;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ADDRESSColumn {
                get {
                    return this.columnADDRESS;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn CHECK_ADDRESSColumn {
                get {
                    return this.columnCHECK_ADDRESS;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SeqNoColumn {
                get {
                    return this.columnSeqNo;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public UnitInitialDataInfoRow this[int index] {
                get {
                    return ((UnitInitialDataInfoRow)(this.Rows[index]));
                }
            }
            
            public event UnitInitialDataInfoRowChangeEventHandler UnitInitialDataInfoRowChanging;
            
            public event UnitInitialDataInfoRowChangeEventHandler UnitInitialDataInfoRowChanged;
            
            public event UnitInitialDataInfoRowChangeEventHandler UnitInitialDataInfoRowDeleting;
            
            public event UnitInitialDataInfoRowChangeEventHandler UnitInitialDataInfoRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddUnitInitialDataInfoRow(UnitInitialDataInfoRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public UnitInitialDataInfoRow AddUnitInitialDataInfoRow(int UNIT_NO, int ID, string NAME, string DVNAME, string TYPE, string FORMAT, string LOW_VALUE, string HIGH_VALUE, int WORD_SIZE, int POINT, string UNIT, string ValueType, string ADDRESS, string CHECK_ADDRESS, int SeqNo) {
                UnitInitialDataInfoRow rowUnitInitialDataInfoRow = ((UnitInitialDataInfoRow)(this.NewRow()));
                rowUnitInitialDataInfoRow.ItemArray = new object[] {
                        UNIT_NO,
                        ID,
                        NAME,
                        DVNAME,
                        TYPE,
                        FORMAT,
                        LOW_VALUE,
                        HIGH_VALUE,
                        WORD_SIZE,
                        POINT,
                        UNIT,
                        ValueType,
                        ADDRESS,
                        CHECK_ADDRESS,
                        SeqNo};
                this.Rows.Add(rowUnitInitialDataInfoRow);
                return rowUnitInitialDataInfoRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                UnitInitialDataInfoDataTable cln = ((UnitInitialDataInfoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new UnitInitialDataInfoDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnUNIT_NO = base.Columns["UNIT NO"];
                this.columnID = base.Columns["ID"];
                this.columnNAME = base.Columns["NAME"];
                this.columnDVNAME = base.Columns["DVNAME"];
                this.columnTYPE = base.Columns["TYPE"];
                this.columnFORMAT = base.Columns["FORMAT"];
                this.columnLOW_VALUE = base.Columns["LOW VALUE"];
                this.columnHIGH_VALUE = base.Columns["HIGH VALUE"];
                this.columnWORD_SIZE = base.Columns["WORD SIZE"];
                this.columnPOINT = base.Columns["POINT"];
                this.columnUNIT = base.Columns["UNIT"];
                this.columnValueType = base.Columns["ValueType"];
                this.columnADDRESS = base.Columns["ADDRESS"];
                this.columnCHECK_ADDRESS = base.Columns["CHECK ADDRESS"];
                this.columnSeqNo = base.Columns["SeqNo"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnUNIT_NO = new System.Data.DataColumn("UNIT NO", typeof(int), null, System.Data.MappingType.Element);
                this.columnUNIT_NO.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "UNIT_NO");
                this.columnUNIT_NO.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "UNIT_NOColumn");
                this.columnUNIT_NO.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnUNIT_NO");
                this.columnUNIT_NO.ExtendedProperties.Add("Generator_UserColumnName", "UNIT NO");
                base.Columns.Add(this.columnUNIT_NO);
                this.columnID = new System.Data.DataColumn("ID", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID);
                this.columnNAME = new System.Data.DataColumn("NAME", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnNAME);
                this.columnDVNAME = new System.Data.DataColumn("DVNAME", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnDVNAME);
                this.columnTYPE = new System.Data.DataColumn("TYPE", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTYPE);
                this.columnFORMAT = new System.Data.DataColumn("FORMAT", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnFORMAT);
                this.columnLOW_VALUE = new System.Data.DataColumn("LOW VALUE", typeof(string), null, System.Data.MappingType.Element);
                this.columnLOW_VALUE.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "LOW_VALUE");
                this.columnLOW_VALUE.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "LOW_VALUEColumn");
                this.columnLOW_VALUE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnLOW_VALUE");
                this.columnLOW_VALUE.ExtendedProperties.Add("Generator_UserColumnName", "LOW VALUE");
                base.Columns.Add(this.columnLOW_VALUE);
                this.columnHIGH_VALUE = new System.Data.DataColumn("HIGH VALUE", typeof(string), null, System.Data.MappingType.Element);
                this.columnHIGH_VALUE.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "HIGH_VALUE");
                this.columnHIGH_VALUE.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "HIGH_VALUEColumn");
                this.columnHIGH_VALUE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnHIGH_VALUE");
                this.columnHIGH_VALUE.ExtendedProperties.Add("Generator_UserColumnName", "HIGH VALUE");
                base.Columns.Add(this.columnHIGH_VALUE);
                this.columnWORD_SIZE = new System.Data.DataColumn("WORD SIZE", typeof(int), null, System.Data.MappingType.Element);
                this.columnWORD_SIZE.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "WORD_SIZE");
                this.columnWORD_SIZE.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "WORD_SIZEColumn");
                this.columnWORD_SIZE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnWORD_SIZE");
                this.columnWORD_SIZE.ExtendedProperties.Add("Generator_UserColumnName", "WORD SIZE");
                base.Columns.Add(this.columnWORD_SIZE);
                this.columnPOINT = new System.Data.DataColumn("POINT", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOINT);
                this.columnUNIT = new System.Data.DataColumn("UNIT", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnUNIT);
                this.columnValueType = new System.Data.DataColumn("ValueType", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnValueType);
                this.columnADDRESS = new System.Data.DataColumn("ADDRESS", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnADDRESS);
                this.columnCHECK_ADDRESS = new System.Data.DataColumn("CHECK ADDRESS", typeof(string), null, System.Data.MappingType.Element);
                this.columnCHECK_ADDRESS.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "CHECK_ADDRESS");
                this.columnCHECK_ADDRESS.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "CHECK_ADDRESSColumn");
                this.columnCHECK_ADDRESS.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnCHECK_ADDRESS");
                this.columnCHECK_ADDRESS.ExtendedProperties.Add("Generator_UserColumnName", "CHECK ADDRESS");
                base.Columns.Add(this.columnCHECK_ADDRESS);
                this.columnSeqNo = new System.Data.DataColumn("SeqNo", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSeqNo);
                this.columnNAME.MaxLength = 50;
                this.columnDVNAME.MaxLength = 50;
                this.columnTYPE.MaxLength = 10;
                this.columnFORMAT.MaxLength = 15;
                this.columnLOW_VALUE.MaxLength = 15;
                this.columnHIGH_VALUE.MaxLength = 15;
                this.columnUNIT.MaxLength = 10;
                this.columnValueType.MaxLength = 50;
                this.columnADDRESS.MaxLength = 10;
                this.columnCHECK_ADDRESS.MaxLength = 50;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public UnitInitialDataInfoRow NewUnitInitialDataInfoRow() {
                return ((UnitInitialDataInfoRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new UnitInitialDataInfoRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(UnitInitialDataInfoRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UnitInitialDataInfoRowChanged != null)) {
                    this.UnitInitialDataInfoRowChanged(this, new UnitInitialDataInfoRowChangeEvent(((UnitInitialDataInfoRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UnitInitialDataInfoRowChanging != null)) {
                    this.UnitInitialDataInfoRowChanging(this, new UnitInitialDataInfoRowChangeEvent(((UnitInitialDataInfoRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UnitInitialDataInfoRowDeleted != null)) {
                    this.UnitInitialDataInfoRowDeleted(this, new UnitInitialDataInfoRowChangeEvent(((UnitInitialDataInfoRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UnitInitialDataInfoRowDeleting != null)) {
                    this.UnitInitialDataInfoRowDeleting(this, new UnitInitialDataInfoRowChangeEvent(((UnitInitialDataInfoRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveUnitInitialDataInfoRow(UnitInitialDataInfoRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DataSetUnitInitialDataInfo ds = new DataSetUnitInitialDataInfo();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "UnitInitialDataInfoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class UnitInitialDataInfoRow : System.Data.DataRow {
            
            private UnitInitialDataInfoDataTable tableUnitInitialDataInfo;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal UnitInitialDataInfoRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableUnitInitialDataInfo = ((UnitInitialDataInfoDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int UNIT_NO {
                get {
                    try {
                        return ((int)(this[this.tableUnitInitialDataInfo.UNIT_NOColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'UNIT NO\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.UNIT_NOColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID {
                get {
                    try {
                        return ((int)(this[this.tableUnitInitialDataInfo.IDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'ID\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.IDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NAME {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.NAMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'NAME\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.NAMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DVNAME {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.DVNAMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'DVNAME\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.DVNAMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TYPE {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.TYPEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'TYPE\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.TYPEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FORMAT {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.FORMATColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'FORMAT\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.FORMATColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LOW_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.LOW_VALUEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'LOW VALUE\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.LOW_VALUEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HIGH_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.HIGH_VALUEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'HIGH VALUE\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.HIGH_VALUEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int WORD_SIZE {
                get {
                    try {
                        return ((int)(this[this.tableUnitInitialDataInfo.WORD_SIZEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'WORD SIZE\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.WORD_SIZEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int POINT {
                get {
                    try {
                        return ((int)(this[this.tableUnitInitialDataInfo.POINTColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'POINT\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.POINTColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UNIT {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.UNITColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'UNIT\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.UNITColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ValueType {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.ValueTypeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'ValueType\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.ValueTypeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ADDRESS {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.ADDRESSColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'ADDRESS\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.ADDRESSColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CHECK_ADDRESS {
                get {
                    try {
                        return ((string)(this[this.tableUnitInitialDataInfo.CHECK_ADDRESSColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'CHECK ADDRESS\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.CHECK_ADDRESSColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int SeqNo {
                get {
                    try {
                        return ((int)(this[this.tableUnitInitialDataInfo.SeqNoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("\'UnitInitialDataInfo\' 테이블의 \'SeqNo\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableUnitInitialDataInfo.SeqNoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUNIT_NONull() {
                return this.IsNull(this.tableUnitInitialDataInfo.UNIT_NOColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUNIT_NONull() {
                this[this.tableUnitInitialDataInfo.UNIT_NOColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIDNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.IDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIDNull() {
                this[this.tableUnitInitialDataInfo.IDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNAMENull() {
                return this.IsNull(this.tableUnitInitialDataInfo.NAMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNAMENull() {
                this[this.tableUnitInitialDataInfo.NAMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDVNAMENull() {
                return this.IsNull(this.tableUnitInitialDataInfo.DVNAMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDVNAMENull() {
                this[this.tableUnitInitialDataInfo.DVNAMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTYPENull() {
                return this.IsNull(this.tableUnitInitialDataInfo.TYPEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTYPENull() {
                this[this.tableUnitInitialDataInfo.TYPEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFORMATNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.FORMATColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFORMATNull() {
                this[this.tableUnitInitialDataInfo.FORMATColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLOW_VALUENull() {
                return this.IsNull(this.tableUnitInitialDataInfo.LOW_VALUEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLOW_VALUENull() {
                this[this.tableUnitInitialDataInfo.LOW_VALUEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHIGH_VALUENull() {
                return this.IsNull(this.tableUnitInitialDataInfo.HIGH_VALUEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHIGH_VALUENull() {
                this[this.tableUnitInitialDataInfo.HIGH_VALUEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWORD_SIZENull() {
                return this.IsNull(this.tableUnitInitialDataInfo.WORD_SIZEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWORD_SIZENull() {
                this[this.tableUnitInitialDataInfo.WORD_SIZEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPOINTNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.POINTColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPOINTNull() {
                this[this.tableUnitInitialDataInfo.POINTColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUNITNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.UNITColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUNITNull() {
                this[this.tableUnitInitialDataInfo.UNITColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsValueTypeNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.ValueTypeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetValueTypeNull() {
                this[this.tableUnitInitialDataInfo.ValueTypeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsADDRESSNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.ADDRESSColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetADDRESSNull() {
                this[this.tableUnitInitialDataInfo.ADDRESSColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCHECK_ADDRESSNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.CHECK_ADDRESSColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCHECK_ADDRESSNull() {
                this[this.tableUnitInitialDataInfo.CHECK_ADDRESSColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSeqNoNull() {
                return this.IsNull(this.tableUnitInitialDataInfo.SeqNoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSeqNoNull() {
                this[this.tableUnitInitialDataInfo.SeqNoColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class UnitInitialDataInfoRowChangeEvent : System.EventArgs {
            
            private UnitInitialDataInfoRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public UnitInitialDataInfoRowChangeEvent(UnitInitialDataInfoRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public UnitInitialDataInfoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Dms.Data.DataSetUnitInitialDataInfoTableAdapters {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.ComponentModel.DataObjectAttribute(true)]
    [System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class UnitInitialDataInfoTableAdapter : System.ComponentModel.Component {
        
        private System.Data.OleDb.OleDbDataAdapter _adapter;
        
        private System.Data.OleDb.OleDbConnection _connection;
        
        private System.Data.OleDb.OleDbCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UnitInitialDataInfoTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private System.Data.OleDb.OleDbDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal System.Data.OleDb.OleDbConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((System.Data.OleDb.OleDbCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected System.Data.OleDb.OleDbCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new System.Data.OleDb.OleDbDataAdapter();
            System.Data.Common.DataTableMapping tableMapping = new System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "UnitInitialDataInfo";
            tableMapping.ColumnMappings.Add("UNIT NO", "UNIT NO");
            tableMapping.ColumnMappings.Add("ID", "ID");
            tableMapping.ColumnMappings.Add("NAME", "NAME");
            tableMapping.ColumnMappings.Add("DVNAME", "DVNAME");
            tableMapping.ColumnMappings.Add("TYPE", "TYPE");
            tableMapping.ColumnMappings.Add("FORMAT", "FORMAT");
            tableMapping.ColumnMappings.Add("LOW VALUE", "LOW VALUE");
            tableMapping.ColumnMappings.Add("HIGH VALUE", "HIGH VALUE");
            tableMapping.ColumnMappings.Add("WORD SIZE", "WORD SIZE");
            tableMapping.ColumnMappings.Add("POINT", "POINT");
            tableMapping.ColumnMappings.Add("UNIT", "UNIT");
            tableMapping.ColumnMappings.Add("ValueType", "ValueType");
            tableMapping.ColumnMappings.Add("ADDRESS", "ADDRESS");
            tableMapping.ColumnMappings.Add("CHECK ADDRESS", "CHECK ADDRESS");
            tableMapping.ColumnMappings.Add("SeqNo", "SeqNo");
            this._adapter.TableMappings.Add(tableMapping);
            this._adapter.InsertCommand = new System.Data.OleDb.OleDbCommand();
            this._adapter.InsertCommand.Connection = this.Connection;
            this._adapter.InsertCommand.CommandText = "INSERT INTO `UnitInitialDataInfo` (`UNIT NO`, `ID`, `NAME`, `DVNAME`, `TYPE`, `FO" +
                "RMAT`, `LOW VALUE`, `HIGH VALUE`, `WORD SIZE`, `POINT`, `UNIT`, `ValueType`, `AD" +
                "DRESS`, `CHECK ADDRESS`, `SeqNo`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?," +
                " ?, ?)";
            this._adapter.InsertCommand.CommandType = System.Data.CommandType.Text;
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("UNIT_NO", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "UNIT NO", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("NAME", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "NAME", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("DVNAME", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "DVNAME", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("TYPE", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "TYPE", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("FORMAT", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "FORMAT", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("LOW_VALUE", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "LOW VALUE", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("HIGH_VALUE", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "HIGH VALUE", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("WORD_SIZE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "WORD SIZE", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("POINT", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "POINT", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("UNIT", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "UNIT", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ValueType", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ValueType", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ADDRESS", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ADDRESS", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("CHECK_ADDRESS", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "CHECK ADDRESS", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("SeqNo", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "SeqNo", System.Data.DataRowVersion.Current, false, null));
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new System.Data.OleDb.OleDbConnection();
            this._connection.ConnectionString = global::Dms.Data.Properties.Settings.Default.DmsUnitInitialDataInfoConnectionString;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new System.Data.OleDb.OleDbCommand[1];
            this._commandCollection[0] = new System.Data.OleDb.OleDbCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "SELECT   UnitInitialDataInfo.*\r\nFROM      UnitInitialDataInfo\r\nORDER BY SeqNo";
            this._commandCollection[0].CommandType = System.Data.CommandType.Text;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(DataSetUnitInitialDataInfo.UnitInitialDataInfoDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual DataSetUnitInitialDataInfo.UnitInitialDataInfoDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            DataSetUnitInitialDataInfo.UnitInitialDataInfoDataTable dataTable = new DataSetUnitInitialDataInfo.UnitInitialDataInfoDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(DataSetUnitInitialDataInfo.UnitInitialDataInfoDataTable dataTable) {
            return this.Adapter.Update(dataTable);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(DataSetUnitInitialDataInfo dataSet) {
            return this.Adapter.Update(dataSet, "UnitInitialDataInfo");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(System.Data.DataRow dataRow) {
            return this.Adapter.Update(new System.Data.DataRow[] {
                        dataRow});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(System.Data.DataRow[] dataRows) {
            return this.Adapter.Update(dataRows);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public virtual int Insert(System.Nullable<int> UNIT_NO, System.Nullable<int> ID, string NAME, string DVNAME, string TYPE, string FORMAT, string LOW_VALUE, string HIGH_VALUE, System.Nullable<int> WORD_SIZE, System.Nullable<int> POINT, string UNIT, string ValueType, string ADDRESS, string CHECK_ADDRESS, System.Nullable<int> SeqNo) {
            if ((UNIT_NO.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[0].Value = ((int)(UNIT_NO.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[0].Value = System.DBNull.Value;
            }
            if ((ID.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[1].Value = ((int)(ID.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[1].Value = System.DBNull.Value;
            }
            if ((NAME == null)) {
                this.Adapter.InsertCommand.Parameters[2].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[2].Value = ((string)(NAME));
            }
            if ((DVNAME == null)) {
                this.Adapter.InsertCommand.Parameters[3].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[3].Value = ((string)(DVNAME));
            }
            if ((TYPE == null)) {
                this.Adapter.InsertCommand.Parameters[4].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[4].Value = ((string)(TYPE));
            }
            if ((FORMAT == null)) {
                this.Adapter.InsertCommand.Parameters[5].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[5].Value = ((string)(FORMAT));
            }
            if ((LOW_VALUE == null)) {
                this.Adapter.InsertCommand.Parameters[6].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[6].Value = ((string)(LOW_VALUE));
            }
            if ((HIGH_VALUE == null)) {
                this.Adapter.InsertCommand.Parameters[7].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[7].Value = ((string)(HIGH_VALUE));
            }
            if ((WORD_SIZE.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[8].Value = ((int)(WORD_SIZE.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[8].Value = System.DBNull.Value;
            }
            if ((POINT.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[9].Value = ((int)(POINT.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[9].Value = System.DBNull.Value;
            }
            if ((UNIT == null)) {
                this.Adapter.InsertCommand.Parameters[10].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[10].Value = ((string)(UNIT));
            }
            if ((ValueType == null)) {
                this.Adapter.InsertCommand.Parameters[11].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[11].Value = ((string)(ValueType));
            }
            if ((ADDRESS == null)) {
                this.Adapter.InsertCommand.Parameters[12].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[12].Value = ((string)(ADDRESS));
            }
            if ((CHECK_ADDRESS == null)) {
                this.Adapter.InsertCommand.Parameters[13].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[13].Value = ((string)(CHECK_ADDRESS));
            }
            if ((SeqNo.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[14].Value = ((int)(SeqNo.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[14].Value = System.DBNull.Value;
            }
            System.Data.ConnectionState previousConnectionState = this.Adapter.InsertCommand.Connection.State;
            if (((this.Adapter.InsertCommand.Connection.State & System.Data.ConnectionState.Open) 
                        != System.Data.ConnectionState.Open)) {
                this.Adapter.InsertCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.InsertCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == System.Data.ConnectionState.Closed)) {
                    this.Adapter.InsertCommand.Connection.Close();
                }
            }
        }
    }
}

#pragma warning restore 1591